server:
  port: 8081

spring:
  datasource:
    username: root
    password: secret
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
            ddl-auto: create-drop
#            ddl-auto: create
            show-sql: true

indexing-settings:
  sites:
    - url: https://centrkinomir.ru/
      name: Centrkinomir
    - url: https://www.playback.ru/
      name: PlayBack.Ru
#    - url: https://fix-price.com
#      name: Fix-price

logging:
  level:
    root:
      info
#     fatal, error, warn, info, debug, trace